# Generated by Django 3.0.8 on 2021-10-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201011_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese_tipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_questao_anamnese', models.CharField(max_length=105)),
                ('resposta_binaria', models.BooleanField()),
                ('habilita_pergunta_secundaria', models.BooleanField()),
                ('descricao_questao_secundaria', models.CharField(max_length=100, null=True)),
                ('resposta_binaria_secundaria', models.BooleanField()),
                ('status_anamnese', models.BooleanField()),
                ('data_criacao', models.CharField(max_length=20, null=True)),
                ('data_modificacao', models.CharField(max_length=20, null=True)),
                ('id_cliente_fk', models.CharField(max_length=105)),
            ],
        ),
        migrations.CreateModel(
            name='Dados_pacotes_procedimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pacote', models.CharField(max_length=100)),
                ('descricao_pacote', models.CharField(max_length=200)),
                ('valor_pacote', models.IntegerField(default=0)),
                ('tipo_pacote', models.CharField(max_length=10)),
                ('qtde_utilizacoes', models.IntegerField(default=0)),
                ('id_cliente_fk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fact_atendimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(max_length=100)),
                ('horario_atendimento', models.CharField(max_length=20)),
                ('possui_pacote_andamento', models.IntegerField(default=0)),
                ('usar_credito_pacote', models.IntegerField(default=0)),
                ('deseja_criar_pacote', models.IntegerField(default=0)),
                ('id_procedimento', models.CharField(max_length=100)),
                ('realizou_pagamento', models.IntegerField(default=0)),
                ('observacao_atendimento', models.CharField(max_length=1000, null=True)),
                ('id_cliente_fk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fact_pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pacote', models.CharField(max_length=10)),
                ('id_procedimento', models.CharField(max_length=100)),
                ('data_inicio_pacote', models.CharField(max_length=20)),
                ('data_termino_pacote', models.CharField(max_length=20)),
                ('campo_adicional_0', models.CharField(max_length=20)),
                ('id_cliente_fk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Governanca_clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auth_user', models.CharField(max_length=100)),
                ('id_cliente_pk', models.CharField(max_length=100)),
                ('contato_1', models.CharField(default=None, max_length=20, null=True)),
                ('contato_2', models.CharField(default=None, max_length=20, null=True)),
                ('permissao_acesso', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('data_criacao', models.CharField(max_length=20, null=True)),
                ('data_modificacao', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato_1', models.CharField(max_length=20, null=True)),
                ('contato_2', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cpf', models.CharField(max_length=20, null=True)),
                ('rg', models.CharField(max_length=20, null=True)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('numero_endereco', models.IntegerField(null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=20, null=True)),
                ('data_nascimento', models.CharField(max_length=20, null=True)),
                ('sexo', models.CharField(max_length=20, null=True)),
                ('profissao', models.CharField(max_length=20, null=True)),
                ('data_criacao', models.CharField(max_length=20, null=True)),
                ('data_modificacao', models.CharField(max_length=20, null=True)),
                ('id_cliente_fk', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_saude_pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(max_length=100)),
                ('id_anamnese_tipo', models.CharField(max_length=100)),
                ('descricao_resposta_anamnese', models.CharField(max_length=1000, null=True)),
                ('descricao_resposta_secundaria_anamnese', models.CharField(max_length=1000, null=True)),
                ('data_criacao', models.CharField(max_length=20, null=True)),
                ('data_modificacao', models.CharField(max_length=20, null=True)),
                ('id_cliente_fk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimentos_individuais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(max_length=100)),
                ('descricao_procedimento', models.CharField(max_length=200)),
                ('valor_procedimento', models.IntegerField(default=0)),
                ('id_cliente_fk', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Historico_pacotes',
        ),
        migrations.DeleteModel(
            name='Ident_dispenser',
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
