# Generated by Django 3.0.8 on 2022-01-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20220104_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_atendimentos_procedimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atendimento', models.CharField(max_length=30)),
                ('id_paciente', models.CharField(max_length=100)),
                ('inicio_atendimento', models.CharField(max_length=20)),
                ('final_atendimento', models.CharField(max_length=20)),
                ('id_procedimento', models.CharField(max_length=100)),
                ('qtde_procedimento', models.IntegerField(default=0)),
                ('nome_procedimento', models.CharField(max_length=100)),
                ('valor_procedimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento_efetuado', models.IntegerField(default=0)),
                ('observacao_atendimento', models.CharField(max_length=1000, null=True)),
                ('data_criacao', models.CharField(max_length=20, null=True)),
                ('data_modificacao', models.CharField(max_length=20, null=True)),
                ('id_cliente_fk', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimentos_individuais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(max_length=100)),
                ('descricao_procedimento', models.CharField(max_length=200)),
                ('valor_procedimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.CharField(max_length=20, null=True)),
                ('data_modificacao', models.CharField(max_length=20, null=True)),
                ('id_cliente_fk', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='anamnese_tipos',
            name='nao_guiada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil_saude_pacientes',
            name='descricao_resposta_anamnese',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
