# Generated by Django 3.0.8 on 2022-01-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20220128_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_atendimentos_procedimentos',
            name='id_atendimento',
            field=models.CharField(max_length=100),
        ),
    ]
